// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR_EVexlj1z--NFC5FT3T0MLVEPweMRb8',
    appId: '1:924709991160:web:f7fe1175d8b84a9bcc010d',
    messagingSenderId: '924709991160',
    projectId: 'parkingapp-ff008',
    authDomain: 'parkingapp-ff008.firebaseapp.com',
    storageBucket: 'parkingapp-ff008.firebasestorage.app',
    measurementId: 'G-8XWWLPFDLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfOqmQofeieq41gnAMHUe9PCCZPJUPZbE',
    appId: '1:924709991160:android:99d0cd5c8487d7b7cc010d',
    messagingSenderId: '924709991160',
    projectId: 'parkingapp-ff008',
    storageBucket: 'parkingapp-ff008.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR_EVexlj1z--NFC5FT3T0MLVEPweMRb8',
    appId: '1:924709991160:web:67c50c869f55d3fbcc010d',
    messagingSenderId: '924709991160',
    projectId: 'parkingapp-ff008',
    authDomain: 'parkingapp-ff008.firebaseapp.com',
    storageBucket: 'parkingapp-ff008.firebasestorage.app',
    measurementId: 'G-4SCS69J0XT',
  );
}
